from django.test import TestCase
from django.contrib.auth.models import User
from .models import Post
# Create your tests here.


class BlogTest(TestCase):
    @classmethod
    def setUpTestData(cls):
        # Create a testuser
        testuser1 = User.objects.create_user(
            username='testuser1', password='12345abc'
        )
        testuser1.save()
        # Create a test post
        test_post = Post.objects.create(
            author=testuser1,
            title='This is test post generated by test.py',
            content='This is the content view of the test post'
        )
        test_post.save()

    def test_post_data(self):
        post = Post.objects.get(id=1)
        author = f'{post.author}'
        title = f'{post.title}'
        content = f'{post.content}'

        self.assertEqual(author, 'testuser1')
        self.assertEqual(title, 'This is test post generated by test.py')
        self.assertEqual(content, 'This is the content view of the test post')
